### ISSUE TITLE
Need to clarify licence and/or add LICENCE file

### ISSUE THREAD

**Issue by krassowski** [bbglab/muts-needle-plot#12]
It would be very nice and useful if @mpschr and contributors were able to clarify licence for this software/repository - I think that more users would choose this module and more PRs will be issued if developers would know what the licence is and what is a general vision for development of this module. If the licence is somewhere, it might be a good idea to create a LICENCE file in the main directory of repository so it would be more visible.

Kind regards and thanks for creating this great piece of software!

**Comment by mpschr** [comment]
Hi!

LICENCE added!

**Comment by krassowski** [comment]
Thank you very much!
