### ISSUE TITLE
Seem to be missing legend?

### ISSUE THREAD

**Issue by jacobhurst** [bbglab/muts-needle-plot#6]
Think, I've got it running ok but the legend does not appear to be there when I select an area with the mouse?

i also had to change the reference in package.json to biojs-sniper to sniper? i used npm to install.

![screenshot from 2015-02-26 17 09 53](https://cloud.githubusercontent.com/assets/216498/6397586/aa6989b8-bddd-11e4-956b-2c91a6918df4.png)

**Comment by mpschr** [comment]
Hi @jacobhurst 

Thanks for reporting!

The biojs-sniper should be working fine. But the dependency was missing until recently from the non-developer dependencies. (see this commit: https://github.com/bbglab/muts-needle-plot/blob/4468fe7c5ef13c67a680e40e1e002441a94d8454/package.json). 

About the legend: It's hard to tell what is goin wrong there. Could you access the chrome or firefox console and see if there is any error message?

Cheers

**Comment by jacobhurst** [comment]
Hi @mpschr 
Thanks for making your code available! Looking in the console it can't see D3... 

![screenshot from 2015-02-27 10 20 52](https://cloud.githubusercontent.com/assets/216498/6410846/881f5314-be6a-11e4-9930-5198ef5e23fd.png)

cheers

**Comment by mpschr** [comment]
Hi,

Here it tries to use the code in the file: ```src/js/d3-svg-legend.js``` and for some reason it is not loaded. Is it missing from the dependencies? I mean, can you see in the HTML if it is being loaded?

A couple of other questions: 
 * Is there the same error for all the examples? 
 * Did you follow the npm-installation guide in the README?

**Comment by jacobhurst** [comment]
The npm install does not work for me, from my history file:- 

  2004  sudo npm install -g npm
 2005  npm run sniper
 2006  cd muts-needle-plot/
 2007  npm run sniper
 2008  sudo npm install -g sniper
 2009  npm run sniper

It then fails on:-

   [03-03-15 09:39:20 l: 1.47] $> npm run sniper

> muts-needle-plot@0.8.0 sniper /home/jacobhurst/play/node_modules/muts-needle-plot
> biojs-sniper .

sh: 1: biojs-sniper: not found

**Comment by mpschr** [comment]
Try installing with ```npm install biojs-sniper```

Anyhow, I was able to install and run the plot with these three commands (I don't know what the -g option does)

 * ```npm install muts-needle-plot```
* ```cd node_modules/muts-needle-plot```
* ```npm run sniper```

The biojs-sniper should be installed automatically. If not, try to install it afterwards with the command on the first line.
